### ISSUE TITLE
not able to detect github token leak

### ISSUE THREAD

**Issue by r3dpars3c** [burak0x01/findsecret#1]
try this.
findsecret -i https://raw.githubusercontent.com/sumanth-manche-sf/pr_sanity_check_tool/d282ea3d7a02965c33d71f89536c969943a5d91a/pr_files.sh

it wont output anything

**Comment by burak0x01** [comment]
This tool is only designed to find hidden keys in Javascript files. The input you gave is a shell script. But in future versions, it will be able to support all file formats. Until then, you can fork the project and disable the regex pattern controlling the js extension.
